import Header from '@/components/Header'
import './globals.css'
import Head from 'next/head'
import { ThemeContextProvider } from '@/components/ThemeContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet"/>
      </Head>
      <body>
        <ThemeContextProvider>
           {children}

        </ThemeContextProvider>
        
        </body>
    </html>
  )
}
